import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { markRevScaleContentPublished, saveRevScaleContent } from "./actions";

const STARTER_CONTENT = [
  { key:"brand-01", title:"Qué hace RevScale después de que entra una consulta", pillar:"Seguimiento", channel:"LINKEDIN_PAGE", format:"CAROUSEL", purpose:"CREDIBILITY", copy:"La mayoría de los sistemas te muestran que el lead existe. RevScale se enfoca en qué debería pasar después: responsable, prioridad, próxima acción y seguimiento visible. Menos memoria. Más proceso comercial.", brief:"Carrusel 5 slides: consulta entra → owner → prioridad → próxima acción → vista manager.", cta:"Ver cómo funciona." },
  { key:"brand-02", title:"Guardado no significa trabajado", pillar:"Revenue leakage", channel:"MULTI", format:"GRAPHIC", purpose:"EDUCATION", copy:"Un lead puede seguir guardado y estar comercialmente perdido. Si no tiene responsable, próxima acción o un seguimiento vigente, el dato existe pero la oportunidad no se está trabajando.", brief:"Gráfico sobrio con contraste Guardado / Trabajado y tres checks operativos.", cta:"¿Qué porcentaje de tus leads activos tiene próxima acción?" },
  { key:"brand-03", title:"Autoresponder no es seguimiento", pillar:"Speed-to-lead", channel:"LINKEDIN_PAGE", format:"TEXT", purpose:"EDUCATION", copy:"Responder automáticamente puede confirmar recepción. No reemplaza una respuesta humana ni garantiza que el lead avance. Por eso RevScale separa automatización de SLA humano y próximo paso.", brief:"Post de texto con captura opcional de SLA, sin claims de performance.", cta:"Medí primera respuesta humana." },
  { key:"brand-04", title:"Matching explicado", pillar:"Matching", channel:"MULTI", format:"CAROUSEL", purpose:"PRODUCT", copy:"Matching útil no es una lista mágica. Es poder explicar por qué una propiedad encaja con una búsqueda y convertir esa coincidencia en una acción concreta para el agente.", brief:"Carrusel: demanda → criterios → propiedad compatible → motivo → acción sugerida.", cta:"Ver matching en RevScale." },
  { key:"brand-05", title:"WhatsApp es canal, no base de datos", pillar:"WhatsApp", channel:"INSTAGRAM", format:"CAROUSEL", purpose:"EDUCATION", copy:"WhatsApp concentra conversaciones, pero no debería ser el lugar donde se decide qué oportunidad sigue viva. RevScale usa el canal sin perder ownership, contexto ni próxima acción.", brief:"Carrusel 6 slides, interfaz real solo si hay screenshot disponible.", cta:"Ordená el seguimiento." },
  { key:"brand-06", title:"Qué debería ver un owner", pillar:"Management", channel:"LINKEDIN_PAGE", format:"DOCUMENT", purpose:"RESOURCE", copy:"Una reunión comercial no debería empezar reconstruyendo memoria. Owner, SLA, seguimientos vencidos, oportunidades por etapa y próxima acción deberían estar visibles antes de empezar.", brief:"Documento/checklist de 1 página para reunión comercial semanal.", cta:"Usalo en tu próxima reunión." },
  { key:"brand-07", title:"CPL no alcanza", pillar:"Marketing ROI", channel:"LINKEDIN_PAGE", format:"TEXT", purpose:"EDUCATION", copy:"El costo por lead sirve para adquisición. Para dirección comercial falta otra parte: qué fuente genera oportunidades que reciben respuesta, avanzan y terminan convirtiendo. La medición debe seguir el recorrido completo.", brief:"Post texto + mini esquema fuente → respuesta → etapa → cierre.", cta:"Seguí la fuente hasta la operación." },
  { key:"brand-08", title:"Qué automatizar y qué dejar humano", pillar:"IA aplicada", channel:"MULTI", format:"CAROUSEL", purpose:"CREDIBILITY", copy:"La IA puede priorizar, resumir contexto y detectar señales. La responsabilidad comercial, la conversación sensible y la decisión de avanzar siguen siendo humanas. RevScale no se vende como un bot que cierra por vos.", brief:"Carrusel dos columnas Automatizar / Mantener humano.", cta:"Automatizá sin perder criterio." },
  { key:"brand-09", title:"Cómo medimos un piloto", pillar:"Proof", channel:"WEBSITE_RESOURCE", format:"RESOURCE", purpose:"PROOF", copy:"Un piloto serio empieza con baseline, define criterios de activación y compara la operación antes y después. No usamos métricas de demo como resultados reales ni prometemos ventas que todavía no podemos atribuir.", brief:"Recurso de una página con baseline, activación, weekly review y día 30/45.", cta:"Conocer Revenue Recovery Pilot." },
  { key:"brand-10", title:"Por qué RevScale no es otro CRM genérico", pillar:"Producto", channel:"LINKEDIN_PAGE", format:"CAROUSEL", purpose:"CREDIBILITY", copy:"RevScale está verticalizado para operación inmobiliaria: qué hacer hoy, respuesta humana, matching explicable, reactivación por eventos y visibilidad de dirección en un mismo flujo.", brief:"Carrusel 6 slides, uno por mecanismo y cierre con tagline.", cta:"Inteligencia comercial inmobiliaria." }
];

export default async function RevScaleContentPage() {
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  const userId = claimsData?.claims?.sub;
  if (!userId) redirect("/auth/login");
  const { data: admin } = await supabase.from("platform_admins").select("user_id").eq("user_id", userId).maybeSingle();
  if (!admin) redirect("/protected");
  const { data: rows } = await supabase.from("b2b_revscale_content").select("*").order("created_at", { ascending: false });
  const existing = new Set((rows || []).map((x) => x.content_key));

  return <main style={{padding:24,maxWidth:1180,margin:"0 auto"}}>
    <p style={{opacity:.65,margin:0}}>GTM · Paso 66</p><h1>Contenido de RevScale</h1>
    <p style={{maxWidth:820,opacity:.78}}>La marca publica producto, educación, recursos y prueba verificable. El founder concentra opinión, aprendizaje y conversación. Este sistema evita mezclar ambos roles.</p>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,margin:"22px 0"}}>{[["Piezas",rows?.length||0],["READY",(rows||[]).filter(x=>x.status==="READY").length],["Publicadas",(rows||[]).filter(x=>x.status==="PUBLISHED").length],["Bloqueadas",(rows||[]).filter(x=>x.status==="BLOCKED").length]].map(([l,v])=><div key={String(l)} style={{border:"1px solid #ddd",borderRadius:14,padding:16}}><div style={{fontSize:28,fontWeight:700}}>{v}</div><div style={{opacity:.7}}>{l}</div></div>)}</div>
    <h2>Biblioteca base</h2>
    <div style={{display:"grid",gap:12}}>{STARTER_CONTENT.map(item=><form key={item.key} action={saveRevScaleContent} style={{border:"1px solid #ddd",borderRadius:14,padding:16}}>
      <input type="hidden" name="content_key" value={item.key}/><input type="hidden" name="title" value={item.title}/><input type="hidden" name="pillar" value={item.pillar}/><input type="hidden" name="channel" value={item.channel}/><input type="hidden" name="format" value={item.format}/><input type="hidden" name="purpose" value={item.purpose}/><input type="hidden" name="post_copy" value={item.copy}/><input type="hidden" name="asset_brief" value={item.brief}/><input type="hidden" name="cta" value={item.cta}/><input type="hidden" name="status" value="READY"/><input type="hidden" name="source_strategy_ref" value="PropertyOS Strategy 2026 · Content authority"/>
      <div style={{display:"flex",justifyContent:"space-between",gap:16}}><div><strong>{item.title}</strong><div style={{opacity:.65,marginTop:4}}>{item.pillar} · {item.channel} · {item.format}</div></div>{!existing.has(item.key)&&<button type="submit">Agregar</button>}</div>
      <p style={{marginBottom:6}}>{item.copy}</p><small style={{opacity:.7}}>CTA: {item.cta}</small>
    </form>)}</div>
    <h2 style={{marginTop:28}}>Contenido gestionado</h2>
    <div style={{display:"grid",gap:12}}>{(rows||[]).map(row=><div key={row.id} style={{border:"1px solid #ddd",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{row.title}</strong><div style={{opacity:.65}}>{row.status} · {row.channel} · {row.format}</div></div></div><p>{row.post_copy}</p>{row.status==="READY"&&<form action={markRevScaleContentPublished} style={{display:"flex",gap:8}}><input type="hidden" name="id" value={row.id}/><input name="publication_url" placeholder="URL publicada" style={{flex:1}}/><button type="submit">Registrar publicación</button></form>}</div>)}{!rows?.length&&<div style={{border:"1px dashed #ccc",borderRadius:14,padding:18,opacity:.7}}>Todavía no hay piezas guardadas.</div>}</div>
  </main>;
}
