import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { googleSearchCampaign } from "@/lib/marketing/google-search-campaign";
import { metaRetargeting } from "@/lib/marketing/meta-retargeting";
import { createOptimizationReview, savePaidSpend } from "./actions";

const input = "w-full rounded-xl border border-[#d2c5b3] bg-white px-3 py-2 text-sm";
function money(value: number | null | undefined) { return value === null || value === undefined ? "—" : `USD ${Number(value).toFixed(2)}`; }
async function getSnapshot(supabase: Awaited<ReturnType<typeof createClient>>, channel: "GOOGLE_SEARCH" | "META_RETARGETING", campaignKey: string) {
  const end = new Date(); const start = new Date(end); start.setDate(end.getDate() - 29); const iso=(d:Date)=>d.toISOString().slice(0,10);
  const { data, error } = await supabase.rpc("get_paid_optimization_snapshot", { p_channel:channel,p_campaign_key:campaignKey,p_period_start:iso(start),p_period_end:iso(end) });
  return error ? null : data;
}

export default async function PaidOptimizationPage({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}) {
  const params = searchParams ? await searchParams : {};
  const supabase = await createClient(); const { data: claims } = await supabase.auth.getClaims(); const userId=claims?.claims?.sub;
  if(!userId) redirect('/auth/login'); const {data:admin}=await supabase.from('platform_admins').select('user_id').eq('user_id',userId).maybeSingle(); if(!admin) redirect('/protected');
  const [google,meta,{count:paidCount},{count:discoveryCount},{data:reviews}] = await Promise.all([
    getSnapshot(supabase,'GOOGLE_SEARCH',googleSearchCampaign.campaignKey), getSnapshot(supabase,'META_RETARGETING',metaRetargeting.campaignKey),
    supabase.from('b2b_opportunities').select('id',{count:'exact',head:true}).eq('stage','PAID').not('paid_at','is',null),
    supabase.from('b2b_discovery_sessions').select('id',{count:'exact',head:true}).eq('status','COMPLETED').eq('disposition','QUALIFIED'),
    supabase.from('b2b_paid_optimization_reviews').select('*').order('created_at',{ascending:false}).limit(12),
  ]);
  const channels=[{name:'Google Search',snapshot:google,key:googleSearchCampaign.campaignKey,channel:'GOOGLE_SEARCH'},{name:'Meta Retargeting',snapshot:meta,key:metaRetargeting.campaignKey,channel:'META_RETARGETING'}] as const;
  const today=new Date().toISOString().slice(0,10); const start=new Date(); start.setDate(start.getDate()-29); const startDate=start.toISOString().slice(0,10);
  return <main className="min-h-screen bg-[#f3ecdf] p-6 text-[#302d28] md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
    <p className="text-[11px] font-semibold uppercase tracking-[.2em] text-[#8d7553]">Fase 10 · Paso 80</p><h1 className="mt-3 font-serif text-4xl">Optimización por demo calificada</h1>
    <p className="mt-3 max-w-4xl text-sm leading-6 text-[#6e665c]">Paid se evalúa por demos que pasaron Discovery/SQL, no por clicks, leads brutos ni CPL. Ajustar o apagar cuando el tráfico sea no-ICP o CPQD supere 25–30% del beneficio bruto esperado del primer año sin señales de mejora.</p>
    {params.error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm">{params.error}</p>}{params.success&&<p className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm">{params.success}</p>}
    <section className="mt-7 grid gap-3 md:grid-cols-4"><Card label="Clientes pagos verificados" value={paidCount||0}/><Card label="Discovery QUALIFIED" value={discoveryCount||0}/><Card label="Guardrail warning" value="25% GP año 1"/><Card label="Guardrail hard" value="30% GP año 1"/></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2">{channels.map(c=>{const s=c.snapshot as any;const spend=s?Number(s.spend_usd||0):0;const qd=s?Number(s.qualified_demo_count||0):0;const cpqd=s?.cost_per_qualified_demo_usd==null?null:Number(s.cost_per_qualified_demo_usd);return <article key={c.key} className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#8d7553]">{c.key}</p><h2 className="mt-2 font-serif text-3xl">{c.name}</h2><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><Metric label="Spend 30d" value={money(spend)}/><Metric label="Demos calificadas" value={qd}/><Metric label="CPQD" value={money(cpqd)}/></div><div className="mt-5 rounded-xl border border-[#ddd1c1] bg-[#f6efe5] p-4 text-sm leading-6 text-[#655e55]">{spend===0?'Sin gasto registrado: todavía no existe dato para optimizar.':qd===0?'Hay gasto pero cero demos calificadas: revisar targeting/keywords, landing y mensaje.':'Ya existe señal para comparar CPQD contra beneficio bruto esperado.'}</div></article>})}</section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2"><form action={savePaidSpend} className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6"><h2 className="font-serif text-2xl">Registrar gasto real</h2><div className="mt-4 grid gap-3"><select name="channel" className={input}><option value="GOOGLE_SEARCH">Google Search</option><option value="META_RETARGETING">Meta Retargeting</option></select><select name="campaign_key" className={input}><option value={googleSearchCampaign.campaignKey}>{googleSearchCampaign.campaignKey}</option><option value={metaRetargeting.campaignKey}>{metaRetargeting.campaignKey}</option></select><input name="spend_date" type="date" defaultValue={today} className={input}/><input name="spend_usd" type="number" step="0.01" min="0" placeholder="Spend USD" className={input}/><div className="grid grid-cols-2 gap-3"><input name="impressions" type="number" min="0" placeholder="Impresiones" className={input}/><input name="clicks" type="number" min="0" placeholder="Clicks" className={input}/></div><input name="source_reference" required placeholder="Referencia verificable: export Ads / invoice / report ID" className={input}/><button className="rounded-xl bg-[#302d28] px-4 py-2 text-sm font-semibold text-white">Guardar spend</button></div></form>
    <form action={createOptimizationReview} className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6"><h2 className="font-serif text-2xl">Generar review</h2><div className="mt-4 grid gap-3"><select name="channel" className={input}><option value="GOOGLE_SEARCH">Google Search</option><option value="META_RETARGETING">Meta Retargeting</option></select><select name="campaign_key" className={input}><option value={googleSearchCampaign.campaignKey}>{googleSearchCampaign.campaignKey}</option><option value={metaRetargeting.campaignKey}>{metaRetargeting.campaignKey}</option></select><div className="grid grid-cols-2 gap-3"><input name="period_start" type="date" defaultValue={startDate} className={input}/><input name="period_end" type="date" defaultValue={today} className={input}/></div><select name="traffic_quality" className={input}><option value="UNKNOWN">Calidad tráfico: por revisar</option><option value="CLEAN">ICP limpia</option><option value="MIXED">Mixta</option><option value="NON_ICP">No-ICP</option></select><input name="expected_first_year_gross_profit_usd" type="number" step="0.01" min="0.01" placeholder="Beneficio bruto esperado año 1 (real)" className={input}/><button className="rounded-xl bg-[#302d28] px-4 py-2 text-sm font-semibold text-white">Calcular y guardar review</button></div></form></section>
    <section className="mt-7 rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6"><h2 className="font-serif text-2xl">Definición de demo calificada</h2><p className="mt-3 text-sm leading-6 text-[#6e665c]">Cuenta solo con Discovery COMPLETED + QUALIFIED + 7/7 criterios confirmados y demo con SHOW. No se usa DEMO_BOOKED, page view ni click como conversión.</p></section>
    <section className="mt-7 rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6"><h2 className="font-serif text-2xl">Últimas decisiones</h2><div className="mt-4 space-y-3">{(reviews||[]).length===0?<p className="text-sm text-[#756c61]">Sin reviews todavía.</p>:(reviews||[]).map((r:any)=><div key={r.id} className="rounded-xl border border-[#ddd1c1] p-4 text-sm"><strong>{r.channel} · {r.verdict}</strong><p className="mt-1 text-[#6e665c]">{r.reason}</p><p className="mt-2 text-xs">Spend {money(r.spend_usd)} · QD {r.qualified_demo_count} · CPQD {money(r.cost_per_qualified_demo_usd)}</p></div>)}</div></section>
  </div></main>;
}
function Card({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-4"><p className="text-xs uppercase tracking-[.12em] text-[#8d7553]">{label}</p><p className="mt-2 font-serif text-2xl">{value}</p></div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-[#ddd1c1] p-3"><p className="text-xs text-[#7b7165]">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
