import { ArrowUpRight, CalendarClock, Flame, MapPinned, Target, Trophy, Users } from "lucide-react";

const territories = [
  {name:"Pocitos · Punta Carretas",zones:"Pocitos, Punta Carretas",owner:"Laura Fernández",prospects:18,target:20,won:5,wonTarget:4,hot:4,priority:"Estratégica"},
  {name:"Carrasco · Parque Miramar",zones:"Carrasco Sur, Carrasco Norte, Parque Miramar",owner:"Santiago Pérez",prospects:14,target:18,won:3,wonTarget:4,hot:3,priority:"Alta"},
  {name:"Malvín · Punta Gorda",zones:"Malvín, Malvín Norte, Punta Gorda",owner:"Mariana Silva",prospects:11,target:16,won:2,wonTarget:3,hot:2,priority:"Alta"},
  {name:"Centro · Cordón",zones:"Cordón, Centro, Parque Rodó",owner:"Diego Rodríguez",prospects:9,target:14,won:2,wonTarget:3,hot:1,priority:"Estándar"},
];
const prospects = [
  ["Ana Pereira","Rambla República del Perú 1420","Pocitos · Punta Carretas","Laura Fernández","Tasación","HOT","Hoy · 17:30"],
  ["Carlos Bianchi","Av. de las Américas 7420","Carrasco · Parque Miramar","Santiago Pérez","Propuesta","HOT","Mañana · 10:00"],
  ["Silvia Gómez","Michigan 1618","Malvín · Punta Gorda","Mariana Silva","Calificado","WARM","Mañana · 15:00"],
  ["Federico Costa","18 de Julio 2145","Centro · Cordón","Diego Rodríguez","Contactado","WARM","28 ago · 11:30"],
];

export default function TerritoriesDemo(){
  const total=territories.reduce((s,t)=>s+t.prospects,0), won=territories.reduce((s,t)=>s+t.won,0), hot=territories.reduce((s,t)=>s+t.hot,0);
  return <main className="min-h-screen p-6 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Inmobiliaria Horizonte · Enterprise</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight text-[#292722] md:text-5xl">Territorios y captación</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55] md:text-[15px]">La inmobiliaria deja de depender de “salir a captar” sin criterio: cada zona tiene responsable, objetivo, pipeline de propietarios y ritmo de seguimiento.</p></div><div className="rounded-xl border border-[#cdbfa9] bg-[#f7f0e6] px-4 py-3 text-sm text-[#655842]"><MapPinned size={16} className="mr-2 inline"/><b>4 territorios activos</b> · Montevideo</div></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<MapPinned size={18}/>} label="Territorios" value="4"/><Metric icon={<Target size={18}/>} label="Prospectos abiertos" value={String(total)}/><Metric icon={<Flame size={18}/>} label="Prioridad HOT" value={String(hot)}/><Metric icon={<CalendarClock size={18}/>} label="Vencidos hoy" value="3"/><Metric icon={<Trophy size={18}/>} label="Captados este mes" value={String(won)}/></section>
    <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><h2 className="font-serif text-3xl text-[#302d28]">Cobertura comercial</h2><p className="mt-1 text-sm text-[#756d63]">Objetivos mensuales por territorio y responsable.</p></div><span className="text-xs text-[#806d52]">Meta total: 14 captaciones</span></div><div className="mt-4 grid gap-4 xl:grid-cols-2">{territories.map(t=><article key={t.name} className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-serif text-2xl text-[#302d28]">{t.name}</h3><p className="mt-1 text-xs text-[#81796e]">{t.zones}</p></div><span className="rounded-full border border-[#c7b79f] px-3 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-[#705d43]">{t.priority}</span></div><div className="mt-5 flex items-center gap-2 text-sm text-[#665e54]"><Users size={15}/>{t.owner}</div><div className="mt-5 grid grid-cols-3 gap-3"><Mini label="Prospectos" value={`${t.prospects}/${t.target}`}/><Mini label="HOT" value={String(t.hot)}/><Mini label="Captados" value={`${t.won}/${t.wonTarget}`}/></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#e1d6c6]"><div className="h-full bg-[#756143]" style={{width:`${Math.min(100,Math.round((t.won/t.wonTarget)*100))}%`}}/></div></article>)}</div></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.42fr]"><div className="overflow-hidden rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6]"><div className="border-b border-[#ddd1c0] px-6 py-4"><h2 className="font-serif text-2xl text-[#302d28]">Pipeline de propietarios</h2><p className="mt-1 text-xs text-[#81796e]">Separado del pipeline de compradores e inquilinos.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#e0d5c5] text-[10px] uppercase tracking-[.13em] text-[#81796e]"><tr><th className="p-4">Propietario</th><th className="p-4">Territorio</th><th className="p-4">Responsable</th><th className="p-4">Etapa</th><th className="p-4">Próximo paso</th></tr></thead><tbody>{prospects.map(p=><tr key={p[0]} className="border-b border-[#e5dacc] last:border-0"><td className="p-4"><b>{p[0]}</b><p className="mt-1 text-xs text-[#81796e]">{p[1]}</p></td><td className="p-4 text-xs">{p[2]}</td><td className="p-4 text-xs">{p[3]}</td><td className="p-4"><span className="rounded-full border border-[#cdbfa9] px-2.5 py-1 text-xs">{p[4]} · {p[5]}</span></td><td className="p-4 text-xs">{p[6]}</td></tr>)}</tbody></table></div></div><aside className="space-y-5"><div className="rounded-2xl border border-[#c8b58d] bg-[#eee5ce] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#7b6548]">Oportunidad del mes</p><p className="mt-3 font-serif text-3xl text-[#302d28]">Pocitos</p><p className="mt-3 text-sm leading-6 text-[#665e54]">La zona ya superó su objetivo de captaciones y mantiene 4 propietarios HOT en trabajo. RevScale permite sostener el ritmo sin perder seguimientos.</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#795f3e]"><ArrowUpRight size={15}/>125% de meta de captación</div></div><div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#8d7553]">Automatización</p><p className="mt-3 text-sm leading-6 text-[#665e54]">Si un seguimiento vence o un territorio queda sin actividad, RevScale avisa al responsable y escala a gestión cuando corresponde.</p></div></aside></section>
  </div></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[.14em]">{label}</span></div><p className="mt-3 font-serif text-3xl text-[#302d28]">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#eee5d7] p-3 text-center"><p className="text-[9px] uppercase tracking-[.12em] text-[#81796e]">{label}</p><p className="mt-1 font-serif text-xl text-[#302d28]">{value}</p></div>}
