import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2, CircleDashed, ExternalLink, Linkedin, UserRoundSearch } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

type Prospect = { id:string; company_name:string; city:string; department:string; decision_maker_name:string|null; decision_maker_role:string|null; decision_maker_linkedin_url:string|null; decision_maker_evidence_url:string|null; decision_maker_quality:"UNKNOWN"|"PARTIAL"|"VERIFIED"; decision_maker_notes:string|null; decision_maker_researched_at:string|null };

export default async function DecisionMakersPage() {
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  const userId = claimsData?.claims?.sub;
  if (!userId) redirect("/auth/login");
  const { data: admin } = await supabase.from("platform_admins").select("user_id").eq("user_id", userId).maybeSingle();
  if (!admin) redirect("/protected");
  const { data } = await supabase.from("b2b_prospects").select("id,company_name,city,department,decision_maker_name,decision_maker_role,decision_maker_linkedin_url,decision_maker_evidence_url,decision_maker_quality,decision_maker_notes,decision_maker_researched_at").order("department",{ascending:true}).order("company_name",{ascending:true});
  const prospects=(data||[]) as Prospect[];
  const verified=prospects.filter(i=>i.decision_maker_quality==="VERIFIED").length;
  const partial=prospects.filter(i=>i.decision_maker_quality==="PARTIAL").length;
  const unknown=prospects.filter(i=>i.decision_maker_quality==="UNKNOWN").length;
  const researched=prospects.filter(i=>i.decision_maker_researched_at).length;
  return <main className="min-h-screen bg-[#f3ecdf] p-6 text-[#302d28] md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/protected/admin/sales/prospects/enrichment" className="inline-flex items-center gap-2 text-sm text-[#7a6e5c]"><ArrowLeft size={15}/> Volver a enrichment</Link><div className="flex flex-wrap gap-2"><Link href="/protected/admin/sales/prospects/phone-whatsapp" className="rounded-lg bg-[#302d28] px-4 py-2.5 text-sm font-semibold text-[#fffaf2]">Teléfono / WhatsApp</Link><Link href="/protected/admin/sales/prospects" className="rounded-lg border border-[#b9aa94] bg-[#fffaf2] px-4 py-2.5 text-sm font-semibold text-[#574936]">Base de prospectos</Link></div></div>
    <div className="mt-6"><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Prospecting · Paso 30</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight md:text-5xl">Owner / Manager</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55]">Identificación del decisor comercial con evidencia profesional pública. UNKNOWN significa investigación completada sin owner, director o manager suficientemente verificable.</p></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Investigadas" value={researched} detail={`de ${prospects.length} cuentas`}/><Metric label="Verificadas" value={verified} detail="cargo/liderazgo explícito"/><Metric label="Parciales" value={partial} detail="referente fuerte sin título formal"/><Metric label="Unknown" value={unknown} detail="sin decisor verificable"/></section>
    <section className="mt-8 overflow-hidden rounded-2xl border border-[#d2c5b3] bg-[#fffaf2]"><div className="overflow-x-auto"><table className="min-w-[1300px] w-full text-left text-sm"><thead className="border-b border-[#ddd1c0] bg-[#eee5d8] text-[10px] font-semibold uppercase tracking-[0.14em] text-[#756b5f]"><tr><th className="p-4">Cuenta</th><th className="p-4">Calidad</th><th className="p-4">Decisor</th><th className="p-4">Rol</th><th className="p-4">LinkedIn</th><th className="p-4">Evidencia</th><th className="p-4">Nota</th></tr></thead><tbody className="divide-y divide-[#e4d9ca]">{prospects.map(item=><tr key={item.id} className="align-top"><td className="p-4"><p className="font-semibold">{item.company_name}</p><p className="mt-1 text-xs text-[#81786d]">{item.city} · {item.department}</p></td><td className="p-4"><Quality value={item.decision_maker_quality}/></td><td className="p-4"><span className="inline-flex items-center gap-2"><UserRoundSearch size={14}/>{item.decision_maker_name||"No verificado"}</span></td><td className="p-4 text-[#625d55]">{item.decision_maker_role||"—"}</td><td className="p-4">{item.decision_maker_linkedin_url?<a href={item.decision_maker_linkedin_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 font-medium text-[#675743] underline decoration-[#a89271] underline-offset-4"><Linkedin size={13}/> Abrir</a>:"—"}</td><td className="p-4">{item.decision_maker_evidence_url?<a href={item.decision_maker_evidence_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 font-medium text-[#675743] underline decoration-[#a89271] underline-offset-4"><ExternalLink size={13}/> Fuente</a>:"—"}</td><td className="p-4 max-w-sm text-xs leading-5 text-[#71695f]">{item.decision_maker_notes||"Sin nota."}</td></tr>)}</tbody></table></div></section>
    <div className="mt-8 rounded-2xl border border-[#cdbfa9] bg-[#efe5d6] p-5 text-sm leading-6 text-[#625d55]"><strong>Regla operativa:</strong> para el primer contacto se prioriza un decisor VERIFIED. PARTIAL orienta el outreach con cautela; UNKNOWN nunca se transforma en un cargo supuesto.</div>
  </div></main>;
}
function Metric({label,value,detail}:{label:string;value:number;detail:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#fffaf2] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#81796e]">{label}</p><p className="mt-3 font-serif text-3xl">{value}</p><p className="mt-1 text-xs text-[#81786d]">{detail}</p></div>}
function Quality({value}:{value:Prospect["decision_maker_quality"]}){const good=value==="VERIFIED";const partial=value==="PARTIAL";return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold ${good?"border-[#aeb99f] bg-[#e4e8dc] text-[#526047]":partial?"border-[#d0b995] bg-[#efe3cf] text-[#795f3d]":"border-[#d0c9bd] bg-[#eeeae3] text-[#726b61]"}`}>{good?<CheckCircle2 size={12}/>:<CircleDashed size={12}/>} {value}</span>}
