export const googleSearchCampaign = {
  campaignKey: "PROPERTYOS_SEARCH_UY_V1",
  name: "PropertyOS | Search | UY | High Intent",
  market: "Uruguay",
  language: "es",
  network: "SEARCH_ONLY",
  landingPath: "/crm-inmobiliario-uruguay",
  finalUrlQuery: "utm_source=google&utm_medium=cpc&utm_campaign=propertyos_search_uy&utm_term={keyword}",
  dailyBudgetUsd: 25,
  testDays: 30,
  testBudgetUsd: 750,
  primaryKpi: "QUALIFIED_DEMO_CPA",
  minimumVerifiedPaidCustomers: 5,
  directLandingConversionsRequired: 1,
  stopRuleGrossProfitRatioWarning: 0.25,
  stopRuleGrossProfitRatioHard: 0.30,
  keywords: [
    { text: "crm inmobiliario uruguay", match: "EXACT" },
    { text: "crm inmobiliario uruguay", match: "PHRASE" },
    { text: "software inmobiliario uruguay", match: "EXACT" },
    { text: "software inmobiliario uruguay", match: "PHRASE" },
    { text: "crm para inmobiliarias", match: "EXACT" },
    { text: "crm para inmobiliarias", match: "PHRASE" },
    { text: "seguimiento leads inmobiliarios", match: "EXACT" },
    { text: "seguimiento leads inmobiliarios", match: "PHRASE" },
    { text: "automatización inmobiliaria", match: "EXACT" },
    { text: "automatización inmobiliaria", match: "PHRASE" },
    { text: "whatsapp inmobiliarias crm", match: "EXACT" },
    { text: "whatsapp inmobiliarias crm", match: "PHRASE" },
  ],
  negativeKeywords: ["empleo","trabajo","sueldo","curso","cursos","gratis","gratuito","descargar","crack","plantilla","excel","casas en venta","apartamentos en venta","apartamentos en alquiler","alquiler de casas","inmuebles en venta","qué es crm","definición crm","tutorial crm"],
  ads: [
    { key: "ad-01", headlines: ["CRM inmobiliario para Uruguay","Priorizá leads y seguimientos","RevScale PropertyOS"], descriptions: ["Convertí consultas de portales y WhatsApp en próximas acciones. Matching, pipeline y control comercial. Ver demo."] },
    { key: "ad-02", headlines: ["Menos leads perdidos","Más operaciones avanzando","RevScale PropertyOS"], descriptions: ["Detectá consultas sin respuesta, seguimientos vencidos y oportunidades para reactivar. Demo de 7 minutos."] },
    { key: "ad-03", headlines: ["Software para inmobiliarias","De consulta a próxima acción","RevScale PropertyOS"], descriptions: ["Centralizá leads, propiedades y seguimiento. Sabé qué oportunidad necesita atención hoy."] },
    { key: "ad-04", headlines: ["CRM + WhatsApp inmobiliario","Con control de seguimiento","RevScale PropertyOS"], descriptions: ["Inbox, contexto y derivación humana. Evitá que el pipeline quede disperso entre chats."] },
    { key: "ad-05", headlines: ["Matching inmobiliario","Demanda + inventario","RevScale PropertyOS"], descriptions: ["Encontrá propiedades compatibles para cada búsqueda y reactivá clientes cuando aparece un motivo real."] },
  ],
} as const;
