export const metaRetargeting = {
  campaignKey: "PROPERTYOS_META_RETARGETING_UY_V1",
  name: "PropertyOS | Meta | Retargeting | UY",
  objective: "LEADS_OR_LANDING_PAGE_VIEWS",
  monthlyBudgetUsd: 400,
  minimumMonthlyBudgetUsd: 300,
  maximumMonthlyBudgetUsd: 500,
  minimumTrafficSignal: "Suficiente tráfico propio para formar audiencias útiles; no activar con audiencias vacías o demasiado pequeñas.",
  pixelEnvKey: "NEXT_PUBLIC_META_PIXEL_ID",
  audiences: [
    { key: "site-30d", name: "Visitantes sitio 30d", source: "WEBSITE", windowDays: 30 },
    { key: "high-intent-30d", name: "Visitantes alta intención 30d", source: "WEBSITE_HIGH_INTENT", windowDays: 30 },
    { key: "demo-viewers-30d", name: "Viewers demo 30d", source: "DEMO_VIEWERS", windowDays: 30 },
    { key: "diagnostic-30d", name: "Visitantes diagnóstico 30d", source: "DIAGNOSTIC_VISITORS", windowDays: 30 },
  ],
  exclusions: ["clientes pagos", "usuarios autenticados", "empleados/admins", "leads ya en proceso comercial cuando pueda excluirse por audiencia first-party"],
  concepts: [
    { key: "meta-01", hook: "Tu CRM puede tener el lead y aun así haberlo perdido.", visual: "Cola de pendientes real, sin estética futurista.", cta: "Diagnosticar", href: "/auditoria-fugas" },
    { key: "meta-02", hook: "¿Quién responde primero mañana?", visual: "Qué hacer hoy.", cta: "Ver demo", href: "/demos" },
    { key: "meta-03", hook: "Autoresponder no es seguimiento.", visual: "SLA humano.", cta: "Ver cómo funciona", href: "/seguimiento-leads-inmobiliarios" },
    { key: "meta-04", hook: "Entró una propiedad nueva. ¿Quién de tu base debería verla?", visual: "Matching.", cta: "Probar matching", href: "/demos" },
    { key: "meta-05", hook: "No vuelvas a escribir ‘¿seguís buscando?’ sin una razón.", visual: "Opportunity Radar.", cta: "Ver reactivación", href: "/casos-de-uso/baja-de-precio-reactivacion" },
    { key: "meta-06", hook: "La reunión comercial no debería empezar con ‘contame qué tenés’.", visual: "Vista Manager.", cta: "Ver tablero", href: "/casos-de-uso/reunion-comercial-lunes" },
    { key: "meta-07", hook: "El CPL no te dice qué portal cierra.", visual: "Marketing ROI.", cta: "Medir fuentes", href: "/casos-de-uso/campana-meta-120-consultas" },
    { key: "meta-08", hook: "WhatsApp es el canal. No debería ser tu base de datos.", visual: "Inbox + lead.", cta: "Ver flujo", href: "/whatsapp-inmobiliarias" },
    { key: "meta-09", hook: "Tomamos 100 leads y te mostramos dónde se corta el proceso.", visual: "Auditoría.", cta: "Pedir diagnóstico", href: "/auditoria-fugas" },
    { key: "meta-10", hook: "No te pedimos cambiar de CRM para probarlo.", visual: "Pilot 45 días.", cta: "Conocer piloto", href: "/demos" },
  ],
} as const;
