import { CheckCircle2, Clock3, FileCheck2, FileSignature, FileText, Fingerprint, LockKeyhole, ShieldCheck } from "lucide-react";

const docs = [
  { ref: "DOC-7A91C0E2F4", title: "Reserva / intención · Martín Rodríguez · Apartamento Pocitos Premium", type: "Reserva", client: "Martín Rodríguez", property: "Apartamento Pocitos Premium", status: "Firmado", review: "Aprobada", date: "26 ago · 14:18" },
  { ref: "DOC-429FB571D1", title: "Oferta de compra · Sofía Fernández · Apartamento Punta Carretas", type: "Oferta de compra", client: "Sofía Fernández", property: "Apartamento Punta Carretas", status: "Enviado", review: "Aprobada", date: "26 ago · 13:42" },
  { ref: "DOC-D2BC6C984A", title: "Solicitud de alquiler · Lucía Moreira · Apartamento Malvín", type: "Solicitud de alquiler", client: "Lucía Moreira", property: "Apartamento Malvín", status: "Visto", review: "No requerida", date: "26 ago · 12:26" },
  { ref: "DOC-F30A6DB893", title: "Arrendamiento · Federico Rossi · Casa Parque Miramar", type: "Arrendamiento", client: "Federico Rossi", property: "Casa Parque Miramar", status: "Generado", review: "Pendiente", date: "26 ago · 11:50" },
  { ref: "DOC-9B12C4E8A0", title: "Reserva / intención · Camila Suárez · Casa Carrasco Sur", type: "Reserva", client: "Camila Suárez", property: "Casa Carrasco Sur", status: "Firmado", review: "Aprobada", date: "25 ago · 18:05" },
];

export default async function DemoDocumentsPage({ searchParams }: { searchParams: Promise<{ plan?: string }> }) {
  const params = await searchParams;
  const enterprise = String(params.plan || "professional").toLowerCase() === "enterprise";
  return <main className="min-h-screen p-6 md:p-8 lg:p-10">
    <div className="mx-auto max-w-7xl">
      <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
        <div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Inmobiliaria Horizonte · Expediente digital</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight text-[#292722] md:text-5xl">Documentos</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55] md:text-[15px]">Reservas, ofertas, solicitudes y contratos nacen desde el CRM, se vinculan a cliente y propiedad y conservan archivo, firma, integridad e historial.</p></div>
        <div className="flex items-center gap-2 rounded-xl border border-[#cdbfa9] bg-[#f7f0e6] px-4 py-3 text-sm text-[#655842]"><ShieldCheck size={17} strokeWidth={1.7} /><span><b>Privado</b> · aislado por inmobiliaria</span></div>
      </div>

      <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<FileText size={18} />} label="Documentos" value="5" /><Metric icon={<Clock3 size={18} />} label="Revisión pendiente" value="1" /><Metric icon={<FileSignature size={18} />} label="Esperando firma" value="2" /><Metric icon={<CheckCircle2 size={18} />} label="Firmados" value="2" /></section>

      <section className="mt-8 grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
        <div className="rounded-2xl border border-[#d2c5b3] bg-[#e9dece] p-6">
          <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#8d7553]">Nuevo documento</p><h2 className="mt-2 font-serif text-3xl text-[#302d28]">Generar desde el CRM</h2><p className="mt-2 text-sm leading-6 text-[#6f675d]">La plantilla recibe los datos del lead y la propiedad sin volver a cargarlos.</p>
          <div className="mt-6 space-y-4"><DemoField label="Plantilla" value="Reserva / intención de operación" /><DemoField label="Lead / cliente" value="Martín Rodríguez · +598 99 123 456" /><DemoField label="Propiedad" value="Apartamento Pocitos Premium · Pocitos" /><label className="block text-xs font-semibold text-[#665e54]"><span className="mb-2 block">Condiciones / observaciones</span><textarea readOnly rows={5} value="Reserva USD 5.000. Vigencia 5 días. Sujeta a revisión de documentación." className="w-full resize-none rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-3 py-2.5 text-sm text-[#39342e]" /></label><button className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#302d28] px-5 py-3 text-sm font-semibold text-[#fffaf2]"><FileCheck2 size={16} /> Generar documento · Demo</button></div>
          <div className="mt-5 rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-4 text-xs leading-5 text-[#756d63]"><b>Autocompletado:</b> cliente, contacto, dirección, zona, moneda, precio, fecha e inmobiliaria. Al generarse, RevScale conserva un snapshot independiente de cambios posteriores en el CRM.</div>
        </div>

        <div className="overflow-hidden rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6]">
          <div className="border-b border-[#ddd1c0] px-6 py-4"><h2 className="font-serif text-2xl text-[#302d28]">Expediente documental</h2><p className="mt-1 text-xs text-[#81796e]">Cada registro tiene referencia única, revisión, firma y trazabilidad.</p></div>
          <div className="divide-y divide-[#e2d7c8]">{docs.map((doc)=><div key={doc.ref} className="px-6 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#8d7553]">{doc.ref}</span><Status value={doc.status} /></div><p className="mt-2 font-semibold text-[#3f3932]">{doc.title}</p><p className="mt-1 text-xs text-[#81796e]">{doc.type} · {doc.client} · {doc.property}</p></div><div className="text-right"><span className={`text-[10px] font-semibold uppercase ${doc.review==="Pendiente"?"text-[#846a42]":doc.review==="Aprobada"?"text-[#596146]":"text-[#81796e]"}`}>Revisión {doc.review.toLowerCase()}</span><p className="mt-2 text-[11px] text-[#8a8176]">{doc.date}</p></div></div></div>)}</div>
        </div>
      </section>

      <section className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
        <div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#8d7553]">Plantillas Horizonte</p><h2 className="mt-2 font-serif text-2xl text-[#302d28]">Biblioteca operativa</h2><div className="mt-5 grid gap-3 md:grid-cols-2"><Template name="Reserva / intención de operación" type="Reserva" review /><Template name="Oferta de compra" type="Oferta de compra" review /><Template name="Solicitud de alquiler" type="Solicitud" /><Template name="Arrendamiento — base para revisión" type="Arrendamiento" review /></div><div className="mt-5 rounded-xl border border-[#d2c5b3] bg-[#eee5d8] p-4 text-xs leading-5 text-[#756d63]">Dirección y Gerencia pueden crear plantillas propias usando variables como <code>{"{{lead.full_name}}"}</code>, <code>{"{{property.title}}"}</code> y <code>{"{{today}}"}</code>.</div></div>

        <div className="rounded-2xl border border-[#cdbfa9] bg-[#e9dece] p-6"><div className="flex items-center gap-2 text-[#765f43]"><FileSignature size={19} /><p className="text-[10px] font-semibold uppercase tracking-[.16em]">Firma electrónica</p></div><h2 className="mt-3 font-serif text-3xl text-[#302d28]">Evidencia de principio a fin.</h2><p className="mt-3 text-sm leading-6 text-[#665e54]">El documento firmado se almacena en privado y el sistema conserva estado, fecha, proveedor, referencia externa, hash y eventos.</p>{enterprise?<div className="mt-5 rounded-xl border border-[#b8c1a4] bg-[#e7eadf] p-5"><div className="flex items-center justify-between gap-2"><b className="text-[#4f5840]">Conector Enterprise</b><span className="rounded-full border border-[#aeb99a] px-2.5 py-1 text-[10px] font-semibold uppercase text-[#596146]">Preparado</span></div><p className="mt-3 text-xs leading-5 text-[#626a54]">TuID / Abitab · convenio y credenciales requeridos para activación real. La demo no simula una firma avanzada inexistente.</p></div>:<div className="mt-5 rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2"><LockKeyhole size={16} /><b className="text-sm text-[#5d5347]">Firma avanzada integrada · Enterprise</b></div><p className="mt-2 text-xs leading-5 text-[#7a7167]">Professional permite registrar firma externa y guardar la copia firmada. Enterprise agrega el conector del proveedor.</p></div>}<div className="mt-5 flex items-start gap-3 rounded-xl border border-[#cdbfa9] bg-[#f7f0e6] p-4"><Fingerprint size={18} className="mt-0.5 shrink-0 text-[#806d52]" /><p className="text-xs leading-5 text-[#756d63]"><b>Integridad:</b> cada snapshot tiene SHA-256. Un documento enviado o finalizado ya no puede cambiar silenciosamente su contenido.</p></div></div>
      </section>

      <section className="mt-8 rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#8d7553]">Ejemplo de auditoría</p><h2 className="mt-2 font-serif text-2xl text-[#302d28]">DOC-7A91C0E2F4 · Reserva firmada</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Audit title="Documento creado" time="14:02" /><Audit title="Revisión aprobada" time="14:07" /><Audit title="Documento enviado" time="14:09" /><Audit title="Firma registrada" time="14:18" /></div><div className="mt-5 flex items-start gap-2 rounded-xl border border-[#d3c6b4] bg-[#f3ebe0] p-4 text-xs leading-5 text-[#6f675d]"><ShieldCheck size={17} className="mt-0.5 shrink-0" /><p><b>Criterio profesional:</b> RevScale gestiona documentos, evidencia y flujo de firma, pero no reemplaza la intervención jurídica o notarial cuando el negocio la exige.</p></div></section>
    </div>
  </main>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[.16em]">{label}</span></div><p className="mt-3 font-serif text-3xl text-[#302d28]">{value}</p></div>}
function DemoField({label,value}:{label:string;value:string}){return <label className="block text-xs font-semibold text-[#665e54]"><span className="mb-2 block">{label}</span><div className="rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-3 py-2.5 text-sm font-normal text-[#39342e]">{value}</div></label>}
function Template({name,type,review=false}:{name:string;type:string;review?:boolean}){return <div className="rounded-xl border border-[#ded2c1] bg-[#fffaf2] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#474038]">{name}</p><p className="mt-1 text-xs text-[#81796e]">{type} · v1</p></div><span className="rounded-full border border-[#b9c1aa] bg-[#e8ebdf] px-2.5 py-1 text-[10px] font-semibold text-[#586146]">Activa</span></div><p className="mt-3 text-xs text-[#766e64]">{review?"Revisión requerida antes de enviar o firmar.":"Sin revisión obligatoria configurada."}</p></div>}
function Status({value}:{value:string}){const cls=value==="Firmado"?"border-[#b8c1a4] bg-[#e7eadf] text-[#596146]":value==="Enviado"||value==="Visto"?"border-[#c8b58d] bg-[#eee5ce] text-[#735f34]":"border-[#cfc2b1] bg-[#f3ece2] text-[#756b61]";return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase ${cls}`}>{value}</span>}
function Audit({title,time}:{title:string;time:string}){return <div className="rounded-xl border border-[#ded2c1] bg-[#fffaf2] p-4"><p className="font-semibold text-[#484138]">{title}</p><p className="mt-2 text-xs text-[#81796e]">26 ago · {time}</p></div>}
