import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2, Compass, Save } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { saveDiscovery } from "../actions";

const yn = (value: boolean | null | undefined) => value === true ? "YES" : value === false ? "NO" : "UNKNOWN";

export default async function DiscoveryPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params;
  const messages = await searchParams;
  const supabase = await createClient();
  const { data: claimsData } = await supabase.auth.getClaims();
  const userId = claimsData?.claims?.sub;
  if (!userId) redirect("/auth/login");
  const { data: admin } = await supabase.from("platform_admins").select("user_id").eq("user_id", userId).maybeSingle();
  if (!admin) redirect("/protected");

  const { data: opportunity } = await supabase.from("b2b_opportunities").select("id,company,contact_name,stage,icp_score,tier").eq("id", id).maybeSingle();
  if (!opportunity) notFound();
  const { data: session } = await supabase.from("b2b_discovery_sessions").select("*").eq("opportunity_id", id).order("created_at", { ascending: false }).limit(1).maybeSingle();

  return <main className="min-h-screen bg-[#f3ecdf] p-6 text-[#302d28] md:p-8 lg:p-10"><div className="mx-auto max-w-6xl">
    <Link href={`/protected/admin/sales/${id}`} className="inline-flex items-center gap-2 text-sm text-[#7a6e5c]"><ArrowLeft size={15}/> Volver a la oportunidad</Link>
    <div className="mt-6 rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-6 md:p-8"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#8d7553]">Paso 48 · Discovery</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl">{opportunity.company}</h1><p className="mt-2 text-sm text-[#746c62]">{opportunity.contact_name || "Contacto pendiente"} · etapa {opportunity.stage}</p></div><span className="rounded-full border border-[#cbbda8] bg-[#efe5d6] px-3 py-1 text-xs font-semibold">{opportunity.tier === "UNSCORED" ? "Sin score" : `Tier ${opportunity.tier} · ${opportunity.icp_score}`}</span></div></div>
    {messages.success && <div className="mt-5 rounded-xl border border-[#b7c5aa] bg-[#e5eadf] px-4 py-3 text-sm text-[#4d5c46]">{messages.success}</div>}
    {messages.error && <div className="mt-5 rounded-xl border border-[#d9b7aa] bg-[#f4e4dc] px-4 py-3 text-sm text-[#7b4539]">{messages.error}</div>}
    <div className="mt-6 rounded-2xl border border-[#cdbfa9] bg-[#efe5d6] p-5 text-sm leading-6 text-[#625d55]"><strong>Apertura:</strong> “Antes de mostrarte RevScale, quiero entender cómo entra y se trabaja una consulta hoy. Si ya tienen esta parte muy bien resuelta, probablemente no tenga sentido que cambien nada.”</div>

    <form action={saveDiscovery} className="mt-6 space-y-6"><input type="hidden" name="opportunity_id" value={id}/>
      <Section title="1. Volumen" subtitle="Rangos alcanzan. No forzar cifras confidenciales.">
        <Grid><Field label="Consultas por mes"><input className="field" type="number" name="volume_monthly_inquiries" defaultValue={session?.volume_monthly_inquiries ?? ""}/></Field><Field label="Mix venta / alquiler / desarrollos"><input className="field" name="volume_mix" defaultValue={session?.volume_mix ?? ""}/></Field><Field label="Propiedades activas"><input className="field" type="number" name="active_properties" defaultValue={session?.active_properties ?? ""}/></Field><Field label="Agentes que trabajan leads"><input className="field" type="number" name="agents_working_leads" defaultValue={session?.agents_working_leads ?? ""}/></Field><Field label="Sucursales / equipos"><input className="field" type="number" name="teams_count" defaultValue={session?.teams_count ?? ""}/></Field></Grid>
      </Section>
      <Section title="2. Flujo actual" subtitle="Seguir un lead real de punta a punta."><Grid><Text label="¿Qué pasa cuando entra un lead de InfoCasas?" name="flow_lead_entry" value={session?.flow_lead_entry}/><Text label="¿Y si entra a las 22:15?" name="flow_after_hours" value={session?.flow_after_hours}/><Text label="¿Quién lo asigna?" name="flow_assignment" value={session?.flow_assignment}/><Text label="¿Cuándo consideran que fue atendido?" name="flow_attended_definition" value={session?.flow_attended_definition}/><Text label="¿Dónde queda la conversación?" name="flow_conversation_location" value={session?.flow_conversation_location}/><Text label="¿Cómo registran el próximo paso?" name="flow_next_action" value={session?.flow_next_action}/><Text label="¿Quién controla el seguimiento?" name="flow_followup_control" value={session?.flow_followup_control}/><Text label="¿Qué pasa si el agente no hace nada?" name="flow_no_action" value={session?.flow_no_action}/></Grid></Section>
      <Section title="3. Visibilidad"><Grid><Signal label="¿Saben el tiempo promedio de respuesta?" name="visibility_response_time_known" value={yn(session?.visibility_response_time_known)}/><Field label="Minutos promedio, si lo saben"><input className="field" type="number" name="visibility_response_minutes" defaultValue={session?.visibility_response_minutes ?? ""}/></Field><Signal label="¿Pueden listar leads sin próximo paso?" name="visibility_can_list_no_next_step" value={yn(session?.visibility_can_list_no_next_step)}/><Signal label="¿Ven seguimientos vencidos por agente?" name="visibility_overdue_by_agent" value={yn(session?.visibility_overdue_by_agent)}/><Signal label="¿La reunión comercial sale de datos?" name="visibility_meeting_data_driven" value={yn(session?.visibility_meeting_data_driven)}/><Signal label="¿Saben qué fuente genera operaciones?" name="visibility_source_to_close" value={yn(session?.visibility_source_to_close)}/></Grid></Section>
      <Section title="4. Matching y reactivación"><Grid><Text label="Cuando entra una propiedad nueva, ¿cómo encuentran compradores?" name="matching_new_property" value={session?.matching_new_property}/><Text label="Cuando baja un precio, ¿quién recuerda a quién avisar?" name="matching_price_drop" value={session?.matching_price_drop}/><Field label="% aprox. de la base recontactada por cambios reales"><input className="field" type="number" step="0.01" name="matching_reactivation_pct" defaultValue={session?.matching_reactivation_pct ?? ""}/></Field></Grid></Section>
      <Section title="5. Stack actual"><Grid><Field label="CRM actual"><input className="field" name="stack_crm" defaultValue={session?.stack_crm ?? ""}/></Field><Field label="Quién lo usa todos los días"><input className="field" name="stack_daily_users" defaultValue={session?.stack_daily_users ?? ""}/></Field><Text label="Qué sigue viviendo fuera del CRM" name="stack_outside_crm" value={session?.stack_outside_crm}/><Text label="Qué aman del sistema actual" name="stack_loves" value={session?.stack_loves}/><Text label="Qué no cambiarían" name="stack_wont_change" value={session?.stack_wont_change}/><Text label="Si pudieran arreglar una sola cosa" name="stack_one_fix" value={session?.stack_one_fix}/></Grid></Section>
      <Section title="6. Economía"><Grid><Field label="Inversión aprox. en portales/campañas"><input className="field" name="economics_portal_spend_range" defaultValue={session?.economics_portal_spend_range ?? ""}/></Field><Field label="Valor neto aprox. por operación"><input className="field" name="economics_net_value_per_deal_range" defaultValue={session?.economics_net_value_per_deal_range ?? ""}/></Field><Field label="% consulta → visita"><input className="field" type="number" step="0.01" name="economics_inquiry_to_visit_pct" defaultValue={session?.economics_inquiry_to_visit_pct ?? ""}/></Field><Field label="% visita → cierre"><input className="field" type="number" step="0.01" name="economics_visit_to_close_pct" defaultValue={session?.economics_visit_to_close_pct ?? ""}/></Field></Grid></Section>
      <Section title="7. Síntesis del discovery"><Grid><Text label="Dolor observado, en palabras del prospecto" name="observed_pain" value={session?.observed_pain}/><Text label="Urgencia / trigger" name="urgency_trigger" value={session?.urgency_trigger}/><Field label="Sponsor"><input className="field" name="sponsor_name" defaultValue={session?.sponsor_name ?? ""}/></Field><Field label="Rol del sponsor"><input className="field" name="sponsor_role" defaultValue={session?.sponsor_role ?? ""}/></Field><Text label="Restricciones de implementación" name="implementation_constraints" value={session?.implementation_constraints}/><Text label="Señal de capacidad de cambiar hábitos" name="habit_change_signal" value={session?.habit_change_signal}/><Text label="Caso económico plausible" name="economic_case" value={session?.economic_case}/><Text label="Resumen 3–5 hechos" name="discovery_summary" value={session?.discovery_summary}/><Text label="Próximo paso recomendado" name="next_step_recommendation" value={session?.next_step_recommendation}/></Grid></Section>
      <Section title="8. Qualification" subtitle="No inferir: marcar solo lo que quedó explícitamente confirmado en la conversación."><Grid><Signal label="Dolor explícito" name="qualification_pain_explicit" value={yn(session?.qualification_pain_explicit)}/><Signal label="Volumen suficiente" name="qualification_volume_sufficient" value={yn(session?.qualification_volume_sufficient)}/><Signal label="Sponsor con autoridad" name="qualification_sponsor_authority" value={yn(session?.qualification_sponsor_authority)}/><Signal label="Urgencia o trigger" name="qualification_urgency_trigger" value={yn(session?.qualification_urgency_trigger)}/><Signal label="Stack integrable / migrable" name="qualification_stack_fit" value={yn(session?.qualification_stack_fit)}/><Signal label="Capacidad de cambiar hábitos" name="qualification_habit_change" value={yn(session?.qualification_habit_change)}/><Signal label="Valor económico plausible" name="qualification_economic_value" value={yn(session?.qualification_economic_value)}/><Field label="Disposición final"><select className="field" name="disposition" defaultValue={session?.disposition ?? ""}><option value="">Sin definir</option><option value="QUALIFIED">QUALIFIED → pasar a demo</option><option value="NURTURE">NURTURE → esperar trigger</option><option value="DISQUALIFIED">DISQUALIFIED → cerrar</option></select></Field></Grid></Section>
      <div className="flex flex-wrap gap-3"><button name="complete" value="0" className="inline-flex items-center gap-2 rounded-lg border border-[#a99a84] bg-[#fffaf2] px-5 py-3 text-sm font-semibold"><Save size={15}/> Guardar discovery</button><button name="complete" value="1" className="inline-flex items-center gap-2 rounded-lg bg-[#302d28] px-5 py-3 text-sm font-semibold text-[#fffaf2]"><CheckCircle2 size={15}/> Cerrar discovery</button></div>
    </form>
    <div className="mt-6 rounded-2xl border border-[#c8c1ad] bg-[#e9e7dc] p-5 text-sm leading-6 text-[#625d55]"><span className="inline-flex items-center gap-2 font-semibold"><Compass size={15}/> Regla de avance</span><br/>Solo `QUALIFIED` pasa al Perfect Demo de 7 minutos. Nurture conserva el contacto hasta un trigger; descalificado sale del proceso.</div>
  </div><style>{`.field{width:100%;border:1px solid #cfc1ad;background:#fffaf2;border-radius:.5rem;padding:.7rem .8rem;color:#403b34;outline:none}.field:focus{border-color:#9d8767}`}</style></main>;
}

function Section({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><h2 className="font-serif text-2xl">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-[#81786d]">{subtitle}</p>}<div className="mt-5">{children}</div></section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 md:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[0.14em] text-[#81796e]">{label}</span>{children}</label>}
function Text({label,name,value}:{label:string;name:string;value?:string|null}){return <Field label={label}><textarea className="field resize-y" rows={3} name={name} defaultValue={value ?? ""}/></Field>}
function Signal({label,name,value}:{label:string;name:string;value:string}){return <Field label={label}><select className="field" name={name} defaultValue={value}><option value="UNKNOWN">No confirmado</option><option value="YES">Sí</option><option value="NO">No</option></select></Field>}
