import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function LeakAuditsAdminPage(){
  const supabase=await createClient();
  const {data:claimsData}=await supabase.auth.getClaims(); const userId=claimsData?.claims?.sub; if(!userId)redirect("/auth/login");
  const {data:admin}=await supabase.from("platform_admins").select("user_id").eq("user_id",userId).maybeSingle(); if(!admin)redirect("/protected");
  const {data:rows}=await supabase.from("b2b_leak_audits").select("*").order("created_at",{ascending:false}).limit(100);
  return <main className="min-h-screen bg-[#f3ecdf] p-6 text-[#302d28] md:p-8 lg:p-10"><div className="mx-auto max-w-6xl"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-[#8d7553]">Fase 8 · Paso 70</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl">Auditoría de Fugas</h1><p className="mt-2 max-w-2xl text-sm text-[#625d55]">Resultados resumidos del lead magnet. Las filas originales no se almacenan.</p></div><Link href="/auditoria-fugas" className="rounded-xl border border-[#bda98a] px-4 py-2 text-sm font-semibold">Abrir auditoría pública</Link></div>
  <div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Auditorías",rows?.length||0],["Score medio",rows?.length?Math.round((rows||[]).reduce((a,r)=>a+Number(r.score||0),0)/(rows?.length||1)):"—"],["Con email",(rows||[]).filter(r=>r.contact_email).length]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-5"><p className="text-3xl font-semibold">{v}</p><p className="mt-1 text-sm text-[#746c62]">{l}</p></div>)}</div>
  <div className="mt-7 grid gap-3">{(rows||[]).map(r=><article key={r.id} className="rounded-2xl border border-[#d2c5b3] bg-[#fffaf2] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-serif text-2xl">{r.company||"Inmobiliaria sin identificar"}</h2><p className="mt-1 text-sm text-[#746c62]">{r.contact_name||"Sin nombre"}{r.contact_email?` · ${r.contact_email}`:""}</p><p className="mt-1 text-xs text-[#8a8176]">{new Date(r.created_at).toLocaleString("es-UY")} · {r.row_count} filas · {r.methodology_version}</p></div><div className="rounded-xl bg-[#302d28] px-5 py-3 text-center text-white"><p className="text-xs opacity-70">Score</p><p className="text-3xl font-semibold">{r.score}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-5">{[["Sin owner",r.unowned_count],["Sin próximo",r.no_next_step_count],["Vencidos",r.overdue_followup_count],["Alta intención inactiva",r.high_intent_inactive_count],["Reactivación",r.reactivation_candidate_count]].map(([l,v])=><div key={String(l)} className="rounded-lg border border-[#ddd1c1] p-3"><p className="text-xs text-[#746c62]">{l}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div></article>)}{!rows?.length&&<div className="rounded-2xl border border-dashed border-[#cdbda5] p-8 text-center text-sm text-[#746c62]">Todavía no hay auditorías guardadas.</div>}</div></div></main>;
}
