import { AlertTriangle, CheckCircle2, Clock3, FileWarning, ShieldCheck, Zap } from "lucide-react";

const rules=[
  {name:"Revisión documental pendiente",when:"Documento sin revisión",delay:"24 horas",action:"Escalar a Dirección y Gerencia",active:true},
  {name:"Firma pendiente",when:"Documento enviado sin firma",delay:"48 horas",action:"Avisar al responsable y a gestión",active:true},
  {name:"Documento próximo a vencer",when:"Fecha de vencimiento cercana",delay:"2 días antes",action:"Anticipar el vencimiento",active:true},
  {name:"Reserva sin expediente",when:"Lead en Reserva sin documento",delay:"2 horas",action:"Escalar expediente incompleto",active:true},
];
const history=[
  ["Revisión documental pendiente","DOC-F30A6DB893 · Arrendamiento Parque Miramar requiere revisión","Hoy · 14:15"],
  ["Firma pendiente","DOC-429FB571D1 · Oferta Punta Carretas continúa sin firma","Hoy · 13:45"],
  ["Reserva sin expediente","Martín Rodríguez entró en Reserva sin documento vinculado","Hoy · 12:30"],
];

export default function LegalAutomationsDemo(){return <main className="min-h-screen p-6 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Inmobiliaria Horizonte · Enterprise</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight text-[#292722] md:text-5xl">Control legal</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55] md:text-[15px]">El expediente se vigila incluso cuando nadie tiene RevScale abierto: revisión, firma, vencimientos y documentación de reservas.</p></div><div className="rounded-xl border border-[#cdbfa9] bg-[#f7f0e6] px-4 py-3 text-sm text-[#655842]"><Zap size={16} className="mr-2 inline"/><b>Motor activo</b> · cada 15 minutos</div></div>
  <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CheckCircle2 size={18}/>} label="Reglas activas" value="4/4"/><Metric icon={<FileWarning size={18}/>} label="Revisión pendiente" value="1"/><Metric icon={<Clock3 size={18}/>} label="Esperando firma" value="2"/><Metric icon={<AlertTriangle size={18}/>} label="Vencen pronto" value="1"/></section>
  <section className="mt-8 grid gap-4 xl:grid-cols-2">{rules.map(rule=><article key={rule.name} className="rounded-2xl border border-[#c9b99f] bg-[#f7f0e6] p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-serif text-xl text-[#37312a]">{rule.name}</h2><p className="mt-1 text-xs text-[#81796e]">Control automático del expediente.</p></div><span className="rounded-full border border-[#b7bea8] bg-[#e7eadf] px-3 py-1.5 text-xs font-semibold text-[#596146]">Activa</span></div><div className="mt-5 rounded-xl border border-[#ded2c1] bg-[#fffaf2] p-4 text-sm leading-6 text-[#514a41]"><b className="text-[#795f3e]">Cuando</b> {rule.when}<span className="mx-2 text-[#a08f79]">→</span><b className="text-[#795f3e]">hacer</b> {rule.action}.</div><div className="mt-4 flex items-center justify-between rounded-lg border border-[#d5c8b6] bg-[#eee4d5] px-3 py-2 text-xs text-[#665e54]"><span>Plazo configurado</span><b>{rule.delay}</b></div></article>)}</section>
  <section className="mt-8 grid gap-6 xl:grid-cols-[1fr_.7fr]"><div className="overflow-hidden rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6]"><div className="border-b border-[#ddd1c0] px-6 py-4"><h2 className="font-serif text-2xl text-[#302d28]">Historial legal automático</h2><p className="mt-1 text-xs text-[#81796e]">La demo muestra cómo queda documentado cada control.</p></div>{history.map(([name,summary,date])=><div key={summary} className="border-b border-[#e2d7c8] px-6 py-4 last:border-0"><p className="font-semibold text-[#474038]">{name}</p><p className="mt-1 text-sm text-[#71695f]">{summary}</p><p className="mt-2 text-xs text-[#8a8176]">{date}</p></div>)}</div><aside className="space-y-5"><div className="rounded-2xl border border-[#c8b58d] bg-[#eee5ce] p-6"><div className="flex items-center gap-2 text-[#765f43]"><ShieldCheck size={19}/><p className="text-[10px] font-semibold uppercase tracking-[.16em]">Criterio profesional</p></div><h2 className="mt-3 font-serif text-2xl text-[#302d28]">RevScale no reemplaza al escribano.</h2><p className="mt-3 text-sm leading-6 text-[#665e54]">Controla proceso, evidencia y vencimientos. La revisión jurídica o notarial sigue en manos del profesional cuando corresponde.</p></div><div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#8d7553]">Reserva crítica</p><p className="mt-3 font-serif text-4xl text-[#302d28]">1</p><p className="mt-2 text-xs leading-5 text-[#81796e]">Una oportunidad está en Reserva sin expediente completo y ya fue escalada.</p></div></aside></section>
</div></main>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[.16em]">{label}</span></div><p className="mt-3 font-serif text-3xl text-[#302d28]">{value}</p></div>}
