import { CheckCircle2, CircleDollarSign, Clock3, Eye, ShieldCheck, Users } from "lucide-react";

const rows = [
  { lead: "Martín Rodríguez", operation: "Venta", agent: "Laura Fernández", currency: "USD", deal: 215000, rate: 3, gross: 6450, split: 50, agentAmount: 3225, office: 3225, collected: 3200, status: "Cobro parcial" },
  { lead: "Sofía Fernández", operation: "Venta", agent: "Santiago Pérez", currency: "USD", deal: 268000, rate: 3, gross: 8040, split: 60, agentAmount: 4824, office: 3216, collected: 8040, status: "Pagada" },
  { lead: "Lucía Moreira", operation: "Alquiler", agent: "Mariana Silva", currency: "USD", deal: 1350, rate: 100, gross: 1350, split: 50, agentAmount: 675, office: 675, collected: 0, status: "Pendiente" },
];

export default function DemoCommissionsPage() {
  return <main className="min-h-screen p-6 md:p-8 lg:p-10">
    <div className="mx-auto max-w-7xl">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Inmobiliaria Horizonte · Dirección comercial</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight text-[#292722] md:text-5xl">Comisiones</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55] md:text-[15px]">Controlá cuánto generó cada cierre, cuánto corresponde al agente y qué parte todavía falta cobrar.</p></div>
        <div className="rounded-xl border border-[#cdbfa9] bg-[#f7f0e6] px-4 py-3 text-sm text-[#655842]"><span className="font-semibold">Automático</span> · se crea al pasar una oportunidad a Cierre</div>
      </div>

      <section className="mt-7 grid gap-4 lg:grid-cols-3">
        <AccessCard icon={<ShieldCheck size={18} strokeWidth={1.7} />} title="Director" text="Ve todas las liquidaciones, reglas, totales del equipo, parte del agente, parte de la oficina y puede editar cobros." />
        <AccessCard icon={<Users size={18} strokeWidth={1.7} />} title="Gerente" text="Tiene la misma vista operativa de gestión sobre las comisiones del equipo que administra." />
        <AccessCard icon={<Eye size={18} strokeWidth={1.7} />} title="Agente" text="Solo ve Mi comisión: sus cierres, su split, su importe y el estado de cobro. Nunca ve comisiones de otros agentes ni la parte de la oficina." />
      </section>
      <div className="mt-4 rounded-xl border border-[#d2c5b3] bg-[#eee4d6] px-5 py-4 text-sm leading-6 text-[#665e54]"><strong className="text-[#403a33]">Privacidad real:</strong> esta diferencia no es solo visual. El sistema restringe el acceso por rol y por agente para evitar visibilidad lateral entre compañeros.</div>

      <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={<CircleDollarSign size={18} strokeWidth={1.7} />} label="Liquidaciones" value="3" /><Metric icon={<Clock3 size={18} strokeWidth={1.7} />} label="Pendientes" value="2" /><Metric icon={<CheckCircle2 size={18} strokeWidth={1.7} />} label="Pagadas" value="1" /></section>
      <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Money label="Honorarios · USD" value="US$ 15.840" /><Money label="Cobrado · USD" value="US$ 11.240" /><Money label="Por cobrar · USD" value="US$ 4.600" /><Money label="Agentes · USD" value="US$ 8.724" /></section>

      <section className="mt-9 overflow-hidden rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] shadow-[0_18px_45px_rgba(72,58,40,0.04)]"><div className="border-b border-[#ddd1c0] px-5 py-4 md:px-6"><h2 className="font-serif text-2xl font-medium text-[#302d28]">Liquidaciones por cierre</h2><p className="mt-1 text-xs leading-5 text-[#81796e]">Ejemplo coherente con los leads y agentes que ya aparecen en la demo de Inmobiliaria Horizonte.</p></div><div className="overflow-x-auto"><table className="min-w-[1080px] w-full text-left text-sm"><thead className="bg-[#eee4d6] text-[10px] font-semibold uppercase tracking-[0.12em] text-[#7f7568]"><tr>{["Lead","Operación","Agente","Valor","Honorarios","Comisión bruta","Split","Agente","Oficina","Cobrado","Estado"].map((h)=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.lead} className="border-t border-[#e2d7c8] text-[#514a41]"><Cell strong>{row.lead}</Cell><Cell>{row.operation}</Cell><Cell>{row.agent}</Cell><Cell>{money(row.currency,row.deal)}</Cell><Cell>{row.rate}%</Cell><Cell>{money(row.currency,row.gross)}</Cell><Cell>{row.split}%</Cell><Cell>{money(row.currency,row.agentAmount)}</Cell><Cell>{money(row.currency,row.office)}</Cell><Cell>{money(row.currency,row.collected)}</Cell><Cell><Status value={row.status} /></Cell></tr>)}</tbody></table></div></section>

      <section className="mt-9 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><div className="flex items-start gap-3"><div className="rounded-lg border border-[#d1c3ad] bg-[#eee4d5] p-2 text-[#765f43]"><Users size={18} strokeWidth={1.7} /></div><div><h2 className="font-serif text-2xl font-medium text-[#302d28]">Reglas de comisión</h2><p className="mt-1 text-sm leading-6 text-[#756d63]">Podés tener porcentajes generales o excepciones por agente y tipo de operación.</p></div></div><div className="mt-5 space-y-3"><Rule title="Regla general · Venta" detail="Honorarios 3% · split agente 50%" /><Rule title="Regla general · Alquiler" detail="Honorarios equivalente a 1 mes · split agente 50%" /><Rule title="Santiago Pérez · Venta" detail="Honorarios 3% · split agente 60%" /></div></div><div className="rounded-2xl border border-[#d2c5b3] bg-[#eee4d6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#8d7553]">Cómo funciona</p><h2 className="mt-3 font-serif text-2xl font-medium text-[#302d28]">Del cierre a la liquidación</h2><ol className="mt-5 space-y-4 text-sm leading-6 text-[#665e54]"><li><b className="text-[#423b33]">1.</b> El lead llega a Cierre.</li><li><b className="text-[#423b33]">2.</b> RevScale toma la regla del agente y la operación.</li><li><b className="text-[#423b33]">3.</b> Calcula comisión bruta, split del agente y parte de la oficina.</li><li><b className="text-[#423b33]">4.</b> Dirección o Gerencia confirma el valor real y registra cobros.</li></ol></div></section>
    </div>
  </main>;
}

function AccessCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[0.16em]">Quién puede verlo</span></div><h2 className="mt-3 font-serif text-2xl text-[#37312a]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#6b6359]">{text}</p></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[0.16em]">{label}</span></div><p className="mt-3 font-serif text-3xl font-medium text-[#302d28]">{value}</p></div>}
function Money({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#eee4d6] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#81796e]">{label}</p><p className="mt-2 font-serif text-2xl text-[#37312a]">{value}</p></div>}
function Cell({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <td className={`px-4 py-4 ${strong?"font-semibold text-[#37312a]":""}`}>{children}</td>}
function Rule({title,detail}:{title:string;detail:string}){return <div className="flex items-center justify-between gap-3 rounded-xl border border-[#ded2c1] bg-[#fffaf2] p-4"><div><p className="font-semibold text-[#474038]">{title}</p><p className="mt-1 text-xs text-[#81796e]">{detail}</p></div><span className="text-xs font-semibold text-[#65704d]">Activa</span></div>}
function Status({value}:{value:string}){const cls=value==="Pagada"?"border-[#b8c1a4] bg-[#e7eadf] text-[#596146]":value==="Cobro parcial"?"border-[#c8b58d] bg-[#eee5ce] text-[#735f34]":"border-[#cfc2b1] bg-[#f3ece2] text-[#756b61]";return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${cls}`}>{value}</span>}
function money(currency:string,value:number){return new Intl.NumberFormat("es-UY",{style:"currency",currency,maximumFractionDigits:0}).format(value)}
