"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpRight, FileSpreadsheet, ShieldCheck } from "lucide-react";

type Row = Record<string,string>;
type Audit = {
  row_count:number; score:number; unowned_count:number; no_next_step_count:number; overdue_followup_count:number;
  high_intent_inactive_count:number; reactivation_candidate_count:number; median_age_days:number|null;
  median_first_response_minutes:number|null; stage_distribution:Record<string,number>; metric_snapshot:Record<string,unknown>;
};

const aliases: Record<string,string[]> = {
  id:["id","lead_id","lead id"], entry:["fecha de entrada","fecha_entrada","created_at","created","entry_date","fecha ingreso"],
  source:["fuente","source","lead_source"], owner:["owner","responsable","assigned_to","agente"], stage:["etapa","stage","estado"],
  last:["ultima interaccion","última interacción","last_interaction","last_activity","ultima actividad"], next:["proxima accion","próxima acción","next_action","next step"],
  nextDate:["fecha de proxima accion","fecha de próxima acción","next_action_date","next step date","followup_date"], result:["resultado","result","outcome"],
  firstResponse:["primera respuesta","first_response_at","first response","fecha primera respuesta"]
};
const highIntent = ["visita","visit","negoci","qualified","calific","hot","oferta","proposal","cierre","closing"];

function norm(v:string){return v.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");}
function findHeader(headers:string[], key:string){const targets=aliases[key].map(norm); return headers.find(h=>targets.includes(norm(h)));}
function parseDate(v:string){if(!v) return null; const d=new Date(v); if(!Number.isNaN(d.getTime())) return d; const m=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})(?:\s+(\d{1,2}):(\d{2}))?/); if(!m)return null; const x=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]||0),Number(m[5]||0)); return Number.isNaN(x.getTime())?null:x;}
function median(xs:number[]){if(!xs.length)return null; const s=[...xs].sort((a,b)=>a-b); const m=Math.floor(s.length/2); return s.length%2?s[m]:(s[m-1]+s[m])/2;}
function splitLine(line:string, delimiter:string){const out:string[]=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(c===delimiter&&!q){out.push(cur.trim());cur="";}else cur+=c;}out.push(cur.trim());return out;}
function parseTable(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim()); if(lines.length<2) throw new Error("Necesitamos encabezados y al menos una fila."); const first=lines[0]; const candidates=["\t",";",","]; const delimiter=candidates.sort((a,b)=>first.split(b).length-first.split(a).length)[0]; const headers=splitLine(first,delimiter); return lines.slice(1,5001).map(line=>{const vals=splitLine(line,delimiter); const row:Row={}; headers.forEach((h,i)=>row[h]=vals[i]||"");return row;});}
function analyze(rows:Row[]):Audit{
  if(!rows.length) throw new Error("No encontramos filas para analizar."); const headers=Object.keys(rows[0]); const owner=findHeader(headers,"owner"), stage=findHeader(headers,"stage"), last=findHeader(headers,"last"), next=findHeader(headers,"next"), nextDate=findHeader(headers,"nextDate"), entry=findHeader(headers,"entry"), firstResponse=findHeader(headers,"firstResponse");
  if(!owner || !stage || (!next && !nextDate)) throw new Error("Faltan columnas mínimas: owner/responsable, etapa y próxima acción o fecha de próxima acción.");
  const now=new Date(); const age:number[]=[]; const response:number[]=[]; const stages:Record<string,number>={}; let unowned=0,noNext=0,overdue=0,hi=0,react=0;
  rows.forEach(r=>{if(!r[owner]?.trim())unowned++; const hasNext=Boolean((next&&r[next]?.trim())||(nextDate&&r[nextDate]?.trim())); if(!hasNext)noNext++; const sd=(r[stage]||"Sin etapa").trim()||"Sin etapa"; stages[sd]=(stages[sd]||0)+1; const nd=nextDate?parseDate(r[nextDate]):null; if(nd&&nd<now)overdue++; const ld=last?parseDate(r[last]):null; const ed=entry?parseDate(r[entry]):null; const inactivity=ld?Math.floor((now.getTime()-ld.getTime())/86400000):null; if(highIntent.some(k=>norm(sd).includes(k)) && inactivity!==null && inactivity>=7)hi++; if(inactivity!==null&&inactivity>=14&&(!nd||nd<now))react++; if(ed)age.push(Math.max(0,(now.getTime()-ed.getTime())/86400000)); if(ed&&firstResponse){const fd=parseDate(r[firstResponse]);if(fd&&fd>=ed)response.push((fd.getTime()-ed.getTime())/60000);}});
  const n=rows.length, rate=(x:number)=>x/n; const penalty=rate(unowned)*25+rate(noNext)*25+rate(overdue)*20+rate(hi)*15+rate(react)*15; const score=Math.max(0,Math.min(100,Math.round(100-penalty)));
  return {row_count:n,score,unowned_count:unowned,no_next_step_count:noNext,overdue_followup_count:overdue,high_intent_inactive_count:hi,reactivation_candidate_count:react,median_age_days:median(age),median_first_response_minutes:median(response),stage_distribution:stages,metric_snapshot:{methodology:"leak-audit-v1",weights:{without_owner:25,without_next_step:25,overdue:20,high_intent_inactive:15,reactivation_candidates:15}}};
}
function pct(x:number,n:number){return `${Math.round((x/n)*100)}%`;}

export default function LeakAuditPage(){
  const [raw,setRaw]=useState(""); const [filename,setFilename]=useState(""); const [audit,setAudit]=useState<Audit|null>(null); const [error,setError]=useState(""); const [saved,setSaved]=useState(false); const [company,setCompany]=useState(""); const [name,setName]=useState(""); const [email,setEmail]=useState("");
  const stages=useMemo(()=>audit?Object.entries(audit.stage_distribution).sort((a,b)=>b[1]-a[1]).slice(0,8):[],[audit]);
  async function run(){try{setError("");setSaved(false);setAudit(analyze(parseTable(raw)));}catch(e){setAudit(null);setError(e instanceof Error?e.message:"No pudimos analizar el archivo.");}}
  async function fileChange(file?:File){if(!file)return; if(!/\.(csv|txt)$/i.test(file.name)){setError("Para esta versión usá CSV o pegá directamente las celdas copiadas desde Excel/Sheets.");return;} setFilename(file.name);setRaw(await file.text());setError("");}
  async function save(){if(!audit)return; if(!email.trim()){setError("Ingresá un email para guardar y asociar el diagnóstico.");return;} const res=await fetch("/api/leak-audit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...audit,company,contact_name:name,contact_email:email,source_filename:filename})}); if(!res.ok){setError("El análisis se hizo, pero no pudimos guardar el diagnóstico.");return;}setSaved(true);}
  return <main className="min-h-screen bg-[#efe6d8] text-[#292722]">
    <nav className="border-b border-[#d5c8b6] bg-[#f5eee4]/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="flex items-baseline gap-2"><span className="font-serif text-2xl">RevScale</span><span className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#8a714d]">PropertyOS</span></Link><Link href="/demos" className="text-sm text-[#625d55]">Ver demo</Link></div></nav>
    <section className="mx-auto max-w-6xl px-6 py-14 md:px-8 lg:py-20"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-[#8a714d]">Auditoría de Fugas Comerciales</p><h1 className="mt-4 max-w-4xl font-serif text-5xl leading-[1.03] md:text-6xl">Subí tus leads. Te mostramos dónde se corta el proceso.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#6d665d]">Analizamos ownership, próximos pasos, seguimientos vencidos, inactividad de alta intención, antigüedad, etapas y oportunidades de reactivación. El resultado es un score operativo individual de 0 a 100.</p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">{["Usá una exportación anonimizada: teléfono y email no son necesarios.","Columnas ideales: ID, fecha de entrada, fuente, owner, etapa, última interacción, próxima acción, fecha y resultado.","No es benchmark de mercado ni promesa de ventas: mide disciplina y visibilidad del dataset que cargás."].map(t=><div key={t} className="rounded-2xl border border-[#d5c8b6] bg-[#f7f1e8] p-5 text-sm leading-6 text-[#625d55]"><ShieldCheck className="mb-3 h-5 w-5 text-[#806b4d]"/>{t}</div>)}</div>
      <div className="mt-8 rounded-2xl border border-[#d5c8b6] bg-[#f7f1e8] p-6 md:p-8"><div className="flex items-center gap-3"><FileSpreadsheet className="text-[#806b4d]"/><div><h2 className="font-serif text-3xl">Cargar muestra</h2><p className="mt-1 text-sm text-[#746c62]">CSV hasta 5.000 filas, o copiá y pegá directamente desde Excel/Google Sheets.</p></div></div><input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>fileChange(e.target.files?.[0])} className="mt-6 block w-full text-sm"/><textarea value={raw} onChange={e=>setRaw(e.target.value)} rows={8} placeholder={'id\tfecha de entrada\tfuente\towner\tetapa\tultima interaccion\tproxima accion\tfecha de proxima accion\tresultado'} className="mt-5 w-full rounded-xl border border-[#cdbfaa] bg-[#fffaf2] p-4 font-mono text-xs outline-none"/><button onClick={run} className="mt-4 rounded-xl bg-[#2f2b25] px-6 py-3 font-semibold text-[#f5eee4]">Analizar fugas</button>{error&&<p className="mt-4 rounded-xl border border-[#c9a49a] bg-[#f8e9e4] p-4 text-sm">{error}</p>}</div>
      {audit&&<section className="mt-8 rounded-2xl border border-[#d5c8b6] bg-[#fffaf2] p-6 md:p-8"><div className="grid gap-6 lg:grid-cols-[.35fr_.65fr]"><div className="rounded-2xl bg-[#302d28] p-7 text-[#f7f1e8]"><p className="text-xs uppercase tracking-[.18em] text-[#cbbda9]">Score operativo</p><p className="mt-2 font-serif text-7xl">{audit.score}</p><p className="mt-3 text-sm text-[#d8ccbb]">sobre 100 · metodología leak-audit-v1</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["Sin owner",pct(audit.unowned_count,audit.row_count)],["Sin próximo paso",pct(audit.no_next_step_count,audit.row_count)],["Seguimientos vencidos",audit.overdue_followup_count],["Alta intención inactiva",audit.high_intent_inactive_count],["Reactivación potencial",audit.reactivation_candidate_count],["Antigüedad mediana",audit.median_age_days===null?"No disponible":`${Math.round(audit.median_age_days)} días`]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-[#ddd1c1] bg-[#f7f1e8] p-4"><p className="text-xs text-[#746c62]">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div></div>
        {audit.median_first_response_minutes!==null&&<p className="mt-5 text-sm text-[#625d55]"><strong>Mediana primera respuesta:</strong> {Math.round(audit.median_first_response_minutes)} min, calculada solo porque el dataset incluye una columna de primera respuesta.</p>}
        <div className="mt-7"><h3 className="font-serif text-2xl">Distribución por etapa</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{stages.map(([s,n])=><div key={s} className="flex justify-between rounded-lg border border-[#ddd1c1] px-4 py-3 text-sm"><span>{s}</span><strong>{n}</strong></div>)}</div></div>
        <div className="mt-7 rounded-xl border border-[#cdbfaa] bg-[#efe6d8] p-5"><h3 className="font-serif text-2xl">¿Querés que te muestre cómo RevScale convertiría estas fugas en una cola diaria?</h3><p className="mt-2 text-sm text-[#625d55]">Guardá el diagnóstico para revisarlo en una conversación de 15 minutos. Solo persistimos el resumen; no almacenamos las filas que pegaste o cargaste.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre" className="rounded-lg border border-[#cdbfaa] bg-[#fffaf2] px-3 py-2 text-sm"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Inmobiliaria" className="rounded-lg border border-[#cdbfaa] bg-[#fffaf2] px-3 py-2 text-sm"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="rounded-lg border border-[#cdbfaa] bg-[#fffaf2] px-3 py-2 text-sm"/></div><button onClick={save} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#2f2b25] px-5 py-3 text-sm font-semibold text-white">Guardar diagnóstico <ArrowUpRight size={15}/></button>{saved&&<p className="mt-3 text-sm font-medium">Diagnóstico guardado. Ya está listo para revisión.</p>}</div>
        <p className="mt-5 text-xs leading-5 text-[#81796e]">Score = 100 menos penalizaciones ponderadas por ausencia de owner (25), falta de próximo paso (25), vencimientos (20), alta intención inactiva (15) y oportunidades de reactivación sin seguimiento vigente (15). Es una metodología interna transparente, no un benchmark de mercado.</p>
      </section>}
    </section>
  </main>;
}
