create index if not exists public_site_inquiries_property_idx on public.public_site_inquiries (property_id) where property_id is not null;
create index if not exists public_site_inquiries_publication_idx on public.public_site_inquiries (publication_id) where publication_id is not null;

alter table private.public_site_rate_limits
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'private.public_site_rate_limits'::regclass
      and contype = 'p'
  ) then
    alter table private.public_site_rate_limits
      add constraint public_site_rate_limits_pkey primary key (id);
  end if;
end
$$;
