import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2, ExternalLink, PauseCircle, Radio, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { getCurrentOrganizationContext } from "@/lib/organization-role";
import { planHasFeature } from "@/lib/plan-access";
import { saveMercadoLibrePublication, syncMercadoLibrePublication } from "../actions";

export default async function MercadoLibreDistributionPage() {
  const context = await getCurrentOrganizationContext();
  if (!context) redirect("/auth/login");
  if (!["OWNER", "MANAGER"].includes(context.role)) redirect("/protected");
  if (!planHasFeature(context.plan, "integrations")) redirect("/protected/billing");

  const [{ data: connection }, { data: properties }, { data: publications }] = await Promise.all([
    context.supabase.from("portal_connections").select("id,status,external_account_id,external_account_name,last_sync_at,last_error").eq("organization_id", context.organizationId).eq("provider", "MERCADOLIBRE").maybeSingle(),
    context.supabase.from("properties").select("id,title,property_type,operation,zone,address,price,currency,bedrooms,bathrooms,area_m2,description,status").eq("organization_id", context.organizationId).order("created_at", { ascending: false }),
    context.supabase.from("property_publications").select("id,property_id,status,title,description,address_label,cover_image_url,gallery_urls,contact_name,contact_phone,external_id,external_url,sync_error,last_sync_status,last_synced_at,provider_payload").eq("organization_id", context.organizationId).eq("channel", "MERCADOLIBRE"),
  ]);

  if (connection?.status !== "CONNECTED") redirect("/protected/settings/integrations");
  const publicationByProperty = new Map((publications || []).map((item) => [item.property_id, item]));
  const publishedCount = (publications || []).filter((item) => item.status === "PUBLISHED").length;
  const errorCount = (publications || []).filter((item) => item.last_sync_status === "ERROR").length;

  return <main className="min-h-screen p-6 md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
    <Link href="/protected/distribution" className="inline-flex items-center gap-2 text-sm text-[#7a6e5c]"><ArrowLeft size={15}/> Volver a Publicaciones</Link>
    <div className="mt-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Canal LIVE · Enterprise</p><h1 className="mt-3 font-serif text-4xl font-medium text-[#292722] md:text-5xl">Mercado Libre Inmuebles</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55]">Prepará cada aviso con los identificadores oficiales de categoría y ubicación, validalo contra Mercado Libre y recién después publicalo. RevScale conserva el ID externo, URL, errores y última sincronización.</p></div><div className="rounded-xl border border-[#b7c5aa] bg-[#e5eadf] px-5 py-4"><p className="text-[10px] uppercase tracking-[0.16em] text-[#617055]">Cuenta conectada</p><p className="mt-1 font-semibold text-[#3f503a]">{connection.external_account_name || connection.external_account_id || "Mercado Libre"}</p></div></div>

    <section className="mt-8 grid gap-4 md:grid-cols-3"><Stat label="Propiedades" value={properties?.length || 0} detail="inventario disponible"/><Stat label="Publicadas" value={publishedCount} detail="avisos activos en el canal"/><Stat label="Con error" value={errorCount} detail="requieren revisión"/></section>

    <section className="mt-6 rounded-xl border border-[#cdbfa9] bg-[#eee4d5] p-5 text-sm leading-6 text-[#665f56]"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#705f47]"/><div><p className="font-semibold text-[#403b34]">Publicación segura por etapas</p><p className="mt-1">Guardar no publica nada. <strong>Validar</strong> consulta el validador oficial; <strong>Publicar</strong> crea el aviso; luego <strong>Sincronizar</strong> actualiza título, precio, fotos, ubicación, atributos y descripción. Pausar o reactivar cambia el estado del mismo aviso, sin crear duplicados.</p></div></div></section>

    {connection.last_error && <div className="mt-5 rounded-xl border border-[#d9b7aa] bg-[#f4e4dc] p-4 text-sm text-[#7b4539]">Último error del canal: {connection.last_error}</div>}

    <div className="mt-8 space-y-5">{(properties || []).map((property) => {
      const publication = publicationByProperty.get(property.id);
      const provider = (publication?.provider_payload || {}) as Record<string, string>;
      const hasConfig = Boolean(publication?.id);
      const isPublished = publication?.status === "PUBLISHED";
      const isPaused = publication?.status === "PAUSED";
      return <article key={property.id} className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-5 md:p-6">
        <div className="flex flex-col gap-4 border-b border-[#ded2c1] pb-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><ChannelStatus status={publication?.status || "DRAFT"}/>{publication?.last_sync_status && <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8d7553]">Sync {publication.last_sync_status}</span>}</div><h2 className="mt-3 font-serif text-2xl font-medium text-[#37332d]">{property.title}</h2><p className="mt-2 text-sm text-[#6f675d]">{property.zone || "Zona sin definir"} · {property.price != null ? `${property.currency || ""} ${Number(property.price).toLocaleString("es-UY")}` : "Precio a consultar"}</p>{publication?.external_id && <p className="mt-2 text-xs text-[#81786d]">ID Mercado Libre: {publication.external_id}{publication.last_synced_at ? ` · sync ${new Date(publication.last_synced_at).toLocaleString("es-UY")}` : ""}</p>}</div><div className="flex flex-wrap gap-2"><Link href={`/protected/properties/${property.id}`} className="rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-4 py-2.5 text-sm font-semibold text-[#5f513e]">Ver propiedad</Link>{publication?.external_url && <a href={publication.external_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-4 py-2.5 text-sm font-semibold text-[#5f513e]">Abrir en Mercado Libre <ExternalLink size={14}/></a>}</div></div>

        <form action={saveMercadoLibrePublication} className="mt-5 grid gap-4 lg:grid-cols-2"><input type="hidden" name="property_id" value={property.id}/><Field label="Título del aviso"><input name="ml_title" defaultValue={publication?.title || property.title} className={inputClass}/></Field><Field label="Foto principal (URL)"><input name="ml_cover_image_url" type="url" defaultValue={publication?.cover_image_url || ""} placeholder="https://..." className={inputClass}/></Field><Field label="Categoría oficial"><input name="ml_category_id" defaultValue={provider.category_id || ""} placeholder="Ej. MLU..." className={inputClass}/></Field><Field label="Tipo de publicación"><select name="ml_listing_type_id" defaultValue={provider.listing_type_id || "silver"} className={inputClass}><option value="silver">Silver</option><option value="gold">Gold</option><option value="gold_special">Gold Special</option><option value="gold_premium">Gold Premium</option></select></Field><Field label="Nivel de ubicación"><select name="ml_location_type" defaultValue={provider.location_type || "city"} className={inputClass}><option value="city">Ciudad</option><option value="neighborhood">Barrio</option></select></Field><Field label="ID oficial de ubicación"><input name="ml_location_id" defaultValue={provider.location_id || ""} placeholder="ID de ciudad o barrio" className={inputClass}/></Field><Field label="Dirección"><input name="ml_address_label" defaultValue={publication?.address_label || property.address || ""} className={inputClass}/></Field><Field label="Contacto"><input name="ml_contact_name" defaultValue={publication?.contact_name || ""} placeholder="Nombre del asesor o inmobiliaria" className={inputClass}/></Field><Field label="WhatsApp / teléfono"><input name="ml_contact_phone" defaultValue={publication?.contact_phone || ""} placeholder="598..." className={inputClass}/></Field><Field label="Fotos adicionales"><textarea name="ml_gallery_urls" rows={3} defaultValue={(publication?.gallery_urls || []).join("\n")} placeholder="Una URL por línea" className={inputClass}/></Field><div className="lg:col-span-2"><Field label="Descripción"><textarea name="ml_description" rows={4} defaultValue={publication?.description || property.description || ""} className={inputClass}/></Field></div><div className="lg:col-span-2 flex justify-end border-t border-[#ded2c1] pt-4"><button className="rounded-lg border border-[#b9aa94] bg-[#fffaf2] px-5 py-3 text-sm font-semibold text-[#4d4438]">Guardar preparación</button></div></form>

        {hasConfig && <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-[#ded2c1] pt-4"><form action={syncMercadoLibrePublication}><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="action" value="VALIDATE"/><button className="inline-flex items-center gap-2 rounded-lg border border-[#b9aa94] bg-[#fffaf2] px-4 py-2.5 text-sm font-semibold text-[#4d4438]"><CheckCircle2 size={15}/> Validar</button></form>{!publication.external_id && <form action={syncMercadoLibrePublication}><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="action" value="PUBLISH"/><button className="inline-flex items-center gap-2 rounded-lg bg-[#302d28] px-4 py-2.5 text-sm font-semibold !text-[#fffaf2]"><Send size={15}/> Publicar</button></form>}{publication.external_id && <form action={syncMercadoLibrePublication}><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="action" value="SYNC"/><button className="inline-flex items-center gap-2 rounded-lg bg-[#302d28] px-4 py-2.5 text-sm font-semibold !text-[#fffaf2]"><RefreshCw size={15}/> Sincronizar</button></form>}{isPublished && <form action={syncMercadoLibrePublication}><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="action" value="PAUSE"/><button className="inline-flex items-center gap-2 rounded-lg border border-[#b9aa94] bg-[#eee4d5] px-4 py-2.5 text-sm font-semibold text-[#5f513e]"><PauseCircle size={15}/> Pausar</button></form>}{isPaused && <form action={syncMercadoLibrePublication}><input type="hidden" name="publication_id" value={publication.id}/><input type="hidden" name="action" value="ACTIVATE"/><button className="inline-flex items-center gap-2 rounded-lg border border-[#b9aa94] bg-[#eee4d5] px-4 py-2.5 text-sm font-semibold text-[#5f513e]"><Radio size={15}/> Reactivar</button></form>}</div>}
        {publication?.sync_error && <div className="mt-4 rounded-lg border border-[#d9b7aa] bg-[#f4e4dc] p-3 text-sm text-[#7b4539]">{publication.sync_error}</div>}
      </article>;
    })}</div>
  </div></main>;
}

const inputClass = "mt-2 w-full rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-3 py-2.5 text-sm text-[#37332d] outline-none placeholder:text-[#aaa091] focus:border-[#9f8a6d]";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-[11px] font-semibold uppercase tracking-[0.13em] text-[#756b5f]">{label}{children}</label>; }
function Stat({ label, value, detail }: { label: string; value: number; detail: string }) { return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#8a7a67]">{label}</p><p className="mt-2 font-serif text-3xl text-[#37332d]">{value}</p><p className="mt-1 text-xs text-[#81786d]">{detail}</p></div>; }
function ChannelStatus({ status }: { status: string }) { const labels: Record<string,string> = { DRAFT:"Borrador", READY:"Validado", PUBLISHED:"Publicado", PAUSED:"Pausado", ERROR:"Error" }; return <span className="rounded-full border border-[#cdbfa9] bg-[#fffaf2] px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-[#665942]">{labels[status] || status}</span>; }
