import { ChartNoAxesCombined, CircleDollarSign, MousePointerClick, ReceiptText, Target } from "lucide-react";

const rows = [
  { name: "Meta Ads · Pocitos agosto", spend: "USD 1.850", leads: 41, cpl: "USD 45", visits: 11, reserves: 4, wins: 3, cac: "USD 617", revenue: "USD 8.420", roi: "355%" },
  { name: "InfoCasas · Premium", spend: "USD 1.200", leads: 29, cpl: "USD 41", visits: 9, reserves: 3, wins: 2, cac: "USD 600", revenue: "USD 5.180", roi: "332%" },
  { name: "Google Ads · Carrasco", spend: "USD 980", leads: 17, cpl: "USD 58", visits: 6, reserves: 2, wins: 1, cac: "USD 980", revenue: "USD 2.760", roi: "182%" },
  { name: "Mercado Libre", spend: "USD 700", leads: 24, cpl: "USD 29", visits: 5, reserves: 1, wins: 0, cac: "—", revenue: "USD 0", roi: "-100%" },
];

export default function DemoMarketingRoiPage() {
  return <main className="min-h-screen bg-[#ece4d8] p-6 text-[#302d28] md:p-8 lg:p-10"><div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-[#8d7553]">Revenue Intelligence</p><h1 className="mt-3 font-serif text-4xl font-medium tracking-tight md:text-5xl">Marketing ROI</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#625d55]">La demo muestra cómo RevScale conecta gasto, origen del lead, avance del pipeline y comisión retenida por la inmobiliaria.</p></div><span className="rounded-lg border border-[#c6b79f] bg-[#f7f0e6] px-4 py-2 text-xs font-semibold text-[#665842]">USD · últimos 90 días</span></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<ReceiptText size={18}/>} label="Inversión" value="USD 4.730"/><Metric icon={<CircleDollarSign size={18}/>} label="Ingreso oficina" value="USD 16.360"/><Metric icon={<Target size={18}/>} label="ROI" value="246%"/><Metric icon={<ChartNoAxesCombined size={18}/>} label="Revenue / Spend" value="3,46x"/><Metric icon={<MousePointerClick size={18}/>} label="CAC" value="USD 788"/></section>
    <section className="mt-8 rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#8d7553]">Atribución seleccionada</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-lg border border-[#7a6344] bg-[#d9ccb9] px-3 py-2 text-xs font-semibold">First touch</span><span className="rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-3 py-2 text-xs">Last touch</span><span className="rounded-lg border border-[#cdbfa9] bg-[#fffaf2] px-3 py-2 text-xs">Linear</span></div><p className="mt-4 text-sm text-[#71695f]">En producción el director puede alternar el modelo para entender qué originó la demanda, qué último canal intervino y cómo repartir el crédito cuando hubo varios contactos.</p></section>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Mini label="Leads" value="111"/><Mini label="Calificados" value="54"/><Mini label="Visitas" value="31"/><Mini label="Reservas" value="10"/><Mini label="Cierres" value="6"/><Mini label="Comisión bruta" value="USD 31.900"/></section>
    <section className="mt-8 overflow-x-auto rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6]"><div className="border-b border-[#ded2c1] px-6 py-5"><h2 className="font-serif text-2xl">Rendimiento por campaña / origen</h2><p className="mt-1 text-sm text-[#756e64]">Ejemplo demo con inversión y conversiones coherentes con una inmobiliaria uruguaya.</p></div><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-[10px] uppercase tracking-[0.12em] text-[#887861]"><tr><th className="px-5 py-3">Origen</th><th>Gasto</th><th>Leads</th><th>CPL</th><th>Visitas</th><th>Reservas</th><th>Cierres</th><th>CAC</th><th>Ingreso oficina</th><th>ROI</th></tr></thead><tbody>{rows.map(row=><tr key={row.name} className="border-t border-[#e1d6c7]"><td className="px-5 py-4 font-semibold">{row.name}</td><td>{row.spend}</td><td>{row.leads}</td><td>{row.cpl}</td><td>{row.visits}</td><td>{row.reserves}</td><td>{row.wins}</td><td>{row.cac}</td><td>{row.revenue}</td><td className="font-semibold">{row.roi}</td></tr>)}</tbody></table></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><h2 className="font-serif text-2xl">Decisión sugerida</h2><p className="mt-3 text-sm leading-6 text-[#625d55]">Meta Ads y el paquete Premium de InfoCasas están generando retorno superior a 300%. Mercado Libre trae volumen barato, pero todavía no produjo cierres en el período. El director puede reasignar presupuesto con evidencia de ingresos, no solo cantidad de leads.</p></div><div className="rounded-2xl border border-[#d2c5b3] bg-[#f7f0e6] p-6"><h2 className="font-serif text-2xl">Qué cuenta como ingreso</h2><p className="mt-3 text-sm leading-6 text-[#625d55]">El ROI usa la comisión que queda en la inmobiliaria después del split del agente. El valor de venta de la propiedad y la comisión bruta se muestran por separado para no inflar el retorno.</p></div></section>
  </div></main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-5"><div className="flex items-center gap-2 text-[#806d52]">{icon}<span className="text-[10px] font-semibold uppercase tracking-[0.16em]">{label}</span></div><p className="mt-3 font-serif text-3xl font-medium">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#d2c5b3] bg-[#f7f0e6] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#8d7553]">{label}</p><p className="mt-2 font-serif text-2xl">{value}</p></div>}
